### ISSUE TITLE
Getting error with serviceMonitor

### ISSUE THREAD

**Issue by tyagian** [makezbs/helm-charts#2]
I am not sure what's the issue here. I am getting error with service monitor. Do you have any example, if service name or label should also be there to match with service monitor or there is other reason for this error?

`Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/instance" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/name" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector]`

That's how my servicemonitor looks like:

        
> metrics:
  serviceMonitor:
    enabled:
    namespace: prometheus
    interval: 10s
    selector:
      matchLabels:
        app: query-exporter

**Comment by tyagian** [comment]
Please use PR #3 to fix it

**Comment by ingvarch** [comment]
Merged

**Comment by ingvarch** [comment]
Please use version 0.1.1 - https://github.com/makezbs/helm-charts/releases/tag/query-exporter-0.1.1
